### ISSUE TITLE
selected dates are not updating when i get from server

### ISSUE THREAD

**Issue by AbdulBasitSaleem** [agryva/Some-Calendar#1]
Hello @agryva 

SomeCalendar(
                        mode: SomeMode.Multi,
                        startDate: Jiffy().subtract(years: 3),
                        lastDate: Jiffy().add(months: 9),
                        selectedDates: selectedDates,
                        done: (date) {
                          setState(() {
                            selectedDates = date;
                            showSnackbar(selectedDates.toString());
                          });
                        },
                        onTapFunction: (selectedDate) {
                          print(selectedDate);
                        },
                      ));

- I get 'selected dates' from server,when i got these dates and set it to the calendar, with setState(){};
It did not update the UI. Please also guide me that how can i remove selected date from the list when i tap on that date, If it is already selected

- I don't want to show it as dialog

Thanks

**Comment by agryva** [comment]
- Have you entered the "selected date" from the server in the "selectedDates" parameter in the form of a list?

- UI Calendar without dialog will be present in the next version, please wait 😁`

**Comment by AbdulBasitSaleem** [comment]
-  list of date coming from server, I have set it to the selected dates attribute, but it did not update the UI for those dates
- When next version is coming, waiting for it 

Thanks

**Comment by agryva** [comment]
maybe you can show the code to me for more details 😁

**Comment by AbdulBasitSaleem** [comment]
SomeCalendar(
      mode: SomeMode.Multi,
      startDate: Jiffy().subtract(months: 3),
      lastDate: Jiffy().add(months: 9),
      primaryColor: Color(kPrimaryColor),
      selectedDates: bookedDates,   // these dates are coming from server
      onTapFunction: (selectedDate) {  // this callback i enabled to get a single date click in multiple mode
        if (!_map.containsKey(selectedDate)) {
          newAvailability = NewAvailability();
          newAvailability.date = dateFormat.format(selectedDate);
          newAvailability.startTime = '09:30 AM';
          newAvailability.endTime = '05:30 PM';
          newAvailability.status = true;
          _map[selectedDate] = newAvailability;
        } else {
          _map[selectedDate].status =
              _map[selectedDate].status == true ? false : true;
          _map.update(selectedDate, (v) => _map[selectedDate]);
        }
        setState(() {});

      },
    );


It is not showing selected dates coming from server, when ever I hot restart then it comes

**Comment by agryva** [comment]
please update to some_calendar: ^1.1.3 i've fix a bug

**Comment by AbdulBasitSaleem** [comment]
Thank you i will see this

**Comment by AbdulBasitSaleem** [comment]
@agryva I checked that still it is not showing me the dates, if i have already built a calendar and set selected dates after building the calendar, it does not get update ???

**Comment by agryva** [comment]
variable 'bookedDates' is list a datetime ?

**Comment by AbdulBasitSaleem** [comment]
yes of course it is list of dateTime, but i assign it to selectedDates: when calendar has built.
I am not opening your calendar in dialog

**Comment by agryva** [comment]
"I am not opening your calendar in dialog" 
please try opening this library with dialog is it still a bug ?

**Comment by AbdulBasitSaleem** [comment]
My friend my requirement is not to open calendar in dialog. Can you help me without dialog.

**Comment by agryva** [comment]
@AbdulBasitSaleem please update to "some_calendar: ^1.2.0" i've fix a bug and please to see the Readme.

Thanks

**Comment by AbdulBasitSaleem** [comment]
Good work @agryva. I will give you feedback about this. 

Thank you so much

**Comment by AbdulBasitSaleem** [comment]
@agryva, Thank you for this calendar.
- There is still one problem that if I set selectedDates (coming from server or you can set delay to add dates) after building calendar then it does not show on the calendar, After hot resetting then it shows the selectedDates

**Comment by AbdulBasitSaleem** [comment]
@agryva Please see this code, What i am trying to achieve. May be you get to know. It will be highly
appreciable.
-------------------------------------------------------------------------------------------------------------- 

@override
  Widget build(BuildContext context) {
    double width = MediaQuery.of(context).size.width;
    double height = MediaQuery.of(context).size.height;
    return SafeArea(
      child: Scaffold(
        appBar: AppBar(
          backgroundColor: Color(kPrimaryColor),
          title: Text('Set Availability'),
          centerTitle: true,
        ),
        body: BlocListener(
          bloc: _newAvailabilityBloc,
          listener: (BuildContext context, state) {
            if (state is AvailabilityErrorState) {
              Scaffold.of(context)
                  .showSnackBar(AppGlobal.showMessageInSnackBar(state.error));
            }

            if (state is CreatedNewAvailabilityState) {
              Scaffold.of(context).showSnackBar(
                  AppGlobal.showMessageInSnackBar('Availability is added'));
            }

            if (state is FetchedGuardAvailabilities) {
              if (state.availabilitiesList != null &&
                  state.availabilitiesList.length > 0) {
                newAvailabilitiesList = state.availabilitiesList;
        
                  for (NewAvailability newAvailability
                      in newAvailabilitiesList) {
                    DateTime dateTime = dateFormat.parse(newAvailability.date);
                    listOfAvailabilities.add(dateTime);
                    selectedDates.add(dateTime);    // here i am adding server dates to list, then bloc builder rebuilds UI, but your calendar does not show these dates
                  }
                
              }
            }
          },
          child: BlocBuilder<NewAvailabilityBloc, NewAvailabilityState>(
            builder: (context, state) {
              return ModalProgressHUD(
                inAsyncCall: state is InitialLoadingState ? true : false,
                child: SingleChildScrollView(
                  child: Column(
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    mainAxisSize: MainAxisSize.max,
                    children: <Widget>[
                      Padding(
                        padding: EdgeInsets.all(8.0),
                        child: Column(
                          children: <Widget>[
                            Text(
                              currentDateTime,
                              style: TextStyle(
                                color: Colors.black,
                                fontWeight: FontWeight.bold,
                              ),
                            ),
                            SizedBox(
                              height: 15.0,
                            ),

                          _buildCalendar(),

                            ListView.builder(
                                shrinkWrap: true,
                                physics: NeverScrollableScrollPhysics(),
                                itemCount: manageListViewDates.length,
                                itemBuilder: (context, index) {
                                  return _timeSelectorItem(index);
                                }),
                            SizedBox(
                              height: 20.0,
                            ),
                          ],
                        ),
                      ),
                      StyledButton(
                        color: Color(kPrimaryColor),
                        btnText: 'Save',
                        textColor: Colors.white,
                        borderRadius: 30.0,
                        width: width * 0.65,
                        onPressed: () {
                          List<NewAvailability> data = List();
                          _map.forEach((k, v) => data.add(v));

                          for (int i = 0; i < data.length; i++) {
                            print('date: ${data[i].date}');
                            print('status: ${data[i].status}');
                          }

                          _newAvailabilityBloc.add(AddNewAvailabilityEvent(
                              availabilitiesList: data));
                        },
                      )
                    ],
                  ),
                ),
              );
            },
          ),
        ),
      ),
    );
  }

  Widget _buildCalendar() {
    return SomeCalendar(
      mode: SomeMode.Multi,
      isWithoutDialog: true,
      scrollDirection: Axis.horizontal,
      startDate: Jiffy().subtract(years: 3),
      lastDate: Jiffy().add(months: 9),
      selectedDates: selectedDates,
      done: (date) {},
    );

  }
