### ISSUE TITLE
Clear default dates in range and multiple picker.

### ISSUE THREAD

**Issue by zeiasoroush** [agryva/Some-Calendar#11]
when passing an empty list  to some-calendar you select the 
default dates value(DateTime.now()+4 days).I want to clear the default selected dates.
and let User select dates.
**To Reproduce**
1.SomeCalendar(
                          primaryColor: Color(0xff5833A5),
                          mode: SomeMode.Multi,
                          scrollDirection: Axis.vertical,
                          isWithoutDialog: true,
                          selectedDates: selectedDates,
                          selectedDate: selectedDate,
                          startDate: Jiffy().subtract(years: 3),
                          lastDate: Jiffy().add(months: 9),
                          done: (date) {},
                        ),

![1](https://user-images.githubusercontent.com/35201972/85150145-6b4ff800-b267-11ea-8ab4-ad9cd96a6c39.jpeg)

**Comment by agryva** [comment]
Hii @zeiasoroush 
for the "somecalendar" range mode we deliberately provide a default date to reduce user confusion when using this calendar .
a solution, you might be able to provide users with information before using this calendar that the start date is only an initial value Thanks 😄
