### ISSUE TITLE
Duplicate dates with empty view on last day fo month

### ISSUE THREAD

**Issue by shubhambansal** [agryva/Some-Calendar#12]
**Describe the bug**
I am trying to select a single / range from the view on the last day of the month. While opening the calendar view 30th June is duplicated in all rows and selected by default and other dates are simply empty.

Please see the attached screenshot.
![Screenshot_1593546219](https://user-images.githubusercontent.com/2053026/86170503-83ebc800-bb1b-11ea-8e06-9d57eef933b0.png)

When  I tried to scroll to the next month all looks good.
![Screenshot_1593546239](https://user-images.githubusercontent.com/2053026/86170539-9239e400-bb1b-11ea-94f2-61464ca8afda.png)

Here is the code I am trying to open the calendar view;

```
void _displayDateRangePicker(BuildContext context, TravelState state) async {
    print('show date picker');

    DateTime _startDate = DateTime.now();
    DateTime _endDate = DateTime.now().add(Duration(days: 180));

    showDialog(
        context: context,
        builder: (_) => SomeCalendar(
              mode:
                  (state.tripType is OneWay) ? SomeMode.Single : SomeMode.Range,
              isWithoutDialog: false,
              selectedDate: _startDate,
              startDate: _startDate,
              lastDate: _endDate,
              labels: Labels(
                  dialogRangeFirstDate: 'Departure Date',
                  dialogRangeLastDate: 'Return Date',
                  dialogDone: 'Ok'),
              scrollDirection: Axis.horizontal,
              primaryColor: AppColors.primary,
              done: (date) {
                print(date.toString());
                if (date is DateTime) {
                  _travelBloc.add(TravelEventSelectSingleDate(date));
                } else if (date is List) {
                  _travelBloc.add(TravelEventSelectDateRange(date));
                }
              },
            ));
  }
```

I am not sure If I am doing something wrong or it's a library issue. Please try to provide clarity on this. Overall the library is good and I'd to use this for my app.

**Smartphone (please complete the following information):**
 - Device: Android

**Additional context**

**Comment by agryva** [comment]
Hi @shubhambansal 
Thank you for notifying the bug contained in somecalendar, we fixed it so please update to the latest version.😆😆
